#!/bin/bash 

set -e

# C
if [ "$1" = "c" ]; then
    # Install native dependencies
    apt update
    apt install -y git make build-essential liblzma-dev gcc-arm-linux-gnueabi gcc-aarch64-linux-gnu ccache

    # Configure Git
    git config --global --add safe.directory '*'

    # Get latest iPXE release
    rm -rf ipxe
    git clone https://github.com/ipxe/ipxe.git
    cd ipxe/src
    # We use the latest `master` branch since the release is broken (see https://github.com/ipxe/ipxe/issues/1293),
    # also run `git checkout $(git tag --sort=-v:refname | head -n1)` once there is a release with the fix

    # Enable features
    sed -i -e 's/#undef\tDOWNLOAD_PROTO_HTTPS/#define\tDOWNLOAD_PROTO_HTTPS/g' config/general.h
    sed -i -e 's/\/\/#define PING_CMD/#define PING_CMD/g' config/general.h
    sed -i -e 's/\/\/#define VLAN_CMD/#define VLAN_CMD/g' config/general.h
    sed -i -e 's/\/\/#define REBOOT_CMD/#define REBOOT_CMD/g' config/general.h
    sed -i -e 's/\/\/#define POWEROFF_CMD/#define POWEROFF_CMD/g' config/general.h
    sed -i -e 's/\/\/#define NSLOOKUP_CMD/#define NSLOOKUP_CMD/g' config/general.h
    sed -i -e 's/\/\/#define IPSTAT_CMD/#define IPSTAT_CMD/g' config/general.h
    sed -i -e 's/\/\/#define IMAGE_PNG/#define IMAGE_PNG/g' config/general.h
    sed -i -e 's/\/\/#define CONSOLE_CMD/#define CONSOLE_CMD/g' config/general.h
    sed -i -e 's/\/\/#define CONSOLE_FRAMEBUFFER/#define CONSOLE_FRAMEBUFFER/g' config/console.h
    sed -i -e 's/\/\/#define LOG_LEVEL/#define LOG_LEVEL/g' config/console.h

    # Add the embedded script
    cp ../../config/init.ipxe .

    # Configure make
    # EMBED="init.ipxe"
    EMBEDDED_MAKE() {
        make -j"$(nproc)" "$@"
    }

    # Configure ccache
    ccache -F 0
    ccache -M 0

    # Get ccache stats
    ccache -s

    # Build
    EMBEDDED_MAKE CROSS_COMPILE="ccache " bin-i386-pcbios/ipxe.kpxe
    EMBEDDED_MAKE CROSS_COMPILE="ccache " bin-i386-efi/ipxe.efi
    EMBEDDED_MAKE CROSS_COMPILE="ccache " bin-x86_64-efi/ipxe.efi
    EMBEDDED_MAKE CROSS_COMPILE="ccache arm-linux-gnueabi-" ARCH=arm32 bin-arm32-efi/snp.efi
    EMBEDDED_MAKE CROSS_COMPILE="ccache aarch64-linux-gnu-" ARCH=arm64 bin-arm64-efi/snp.efi
    
    # Build SNP and SNP-only variants for x86 architectures
    EMBEDDED_MAKE CROSS_COMPILE="ccache " bin-i386-efi/snp.efi
    EMBEDDED_MAKE CROSS_COMPILE="ccache " bin-i386-efi/snponly.efi
    EMBEDDED_MAKE CROSS_COMPILE="ccache " bin-x86_64-efi/snp.efi
    EMBEDDED_MAKE CROSS_COMPILE="ccache " bin-x86_64-efi/snponly.efi
    EMBEDDED_MAKE CROSS_COMPILE="ccache arm-linux-gnueabi-" ARCH=arm32 bin-arm32-efi/snponly.efi
    EMBEDDED_MAKE CROSS_COMPILE="ccache aarch64-linux-gnu-" ARCH=arm64 bin-arm64-efi/snponly.efi

    # Output files directly to the final directory
    OUTPUT_DIR="../../out"
    mkdir -p "$OUTPUT_DIR"
    cp bin-i386-pcbios/ipxe.kpxe "$OUTPUT_DIR/ipxe-i386.kpxe"
    cp bin-i386-efi/ipxe.efi "$OUTPUT_DIR/ipxe-i386.efi"
    cp bin-x86_64-efi/ipxe.efi "$OUTPUT_DIR/ipxe-x86_64.efi"
    cp bin-arm32-efi/snp.efi "$OUTPUT_DIR/ipxe-arm32.efi"
    cp bin-arm64-efi/snp.efi "$OUTPUT_DIR/ipxe-arm64.efi"
    
    # Copy SNP variants
    cp bin-i386-efi/snp.efi "$OUTPUT_DIR/snp-i386.efi"
    cp bin-i386-efi/snponly.efi "$OUTPUT_DIR/snponly-i386.efi"
    cp bin-x86_64-efi/snp.efi "$OUTPUT_DIR/snp-x86_64.efi"
    cp bin-x86_64-efi/snponly.efi "$OUTPUT_DIR/snponly-x86_64.efi"
    cp bin-arm32-efi/snponly.efi "$OUTPUT_DIR/snponly-arm32.efi"
    cp bin-arm64-efi/snponly.efi "$OUTPUT_DIR/snponly-arm64.efi"

    # Get ccache stats
    ccache -s

    exit 0
fi
